#!/bin/bash
#SBATCH --account=PAS2229
#SBATCH --time=2:00:00
#SBATCH --job-name=athena
#SBATCH --nodes=7
#SBATCH --ntasks=256
#SBATCH --mail-type=ALL
#SBATCH --export=ALL
#SBATCH --open-mode=append

module load intel/18.0.3
module load intelmpi/2019.7
module load hdf5
module load miniconda3
unset I_MPI_PMI_LIBRARY
set -x
cd $SLURM_SUBMIT_DIR

conda create -n hdf5 python=3.9.7 hdf5=1.10.6 h5py=3.6.0
conda create -n conda_env
source activate conda_env
conda activate hdf5
conda install mpi4py
conda install numpy
conda install hdf5
conda install matplotlib
conda install scipy
conda install -c conda-forge moviepy

###### MAIN OPTIONS ###
MPNS=(1.4 1.6 1.8 2.0)
Lnu=11.2
Mdot=0.7
MachNumber=2.0
RPNS=30        # Integer format (in km) for R_PNS, used for directory names
rMin=3.0e6     # float format (in cm) for R_PNS, used in calculations
RPNS30km=true # 'true' uses the R_PNS = 30km datasets from 1D_OUTPUT_DIR, 'false' selects data from the 1D_OUTPUT_RPNS_DIR directory
physicaltime=3.0e0
outputfreq=3.0e-2
minI=0
maxI=99
nRank=100
eps_nue=12.6156
eps_nueb=18.9234
compile=true
useDefaultIC=true
#### CODE PARAMETERS ####
firstfile=00100
outputnumber=00100
athinputfile=athinput.accretion_MACH_9_25_2023
rMax=1.0e8
rMax_set=220.0 # Maximum radius for some plots
nR=256
nRcell=2
nCores=128
pgen=accretion_SingleNR_FixedKappa_MPNS #accretion_NewTau #accretion_Mach_FullDefinition_Tfloat
pythondir=vis/python
eosdir=../eos_DIR/helm_table.dat
# Get IC files and stash them in StartIC_DIR
if ${RPNS30km}; then
	ENDdatadir=.../1D_OUTPUT_DIR
	ICdir=${ENDdatadir}/Mach_${MachNumber}_DIR/Mdot_${Mdot}_DIR/Lnu_${Lnu}_DIR/Lnu_${Lnu}e51_Mdot_${Mdot}_Mach_${MachNumber}_DIR
	ICtarfile=${ICdir}/Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_RPNS_${RPNS}km.tar.gz
else
	ENDdatadir=../1D_OUTPUT_RPNS_DIR
	ICdir=${ENDdatadir}/Mach_${MachNumber}_DIR/Mdot_${Mdot}_DIR/Lnu_${Lnu}_DIR/RPNS_${RPNS}_DIR/Lnu_${Lnu}e51_Mdot_${Mdot}_Mach_${MachNumber}_DIR
	ICtarfile=${ICdir}/Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_RPNS_${RPNS}km.tar.gz
fi
if ${useDefaultIC}; then
	# replace StartICFiles with default IC files
	echo Using default IC
	rm -rf StartICFiles_DIR/*.athdf
	cp ../default_IC_DIR/*.athdf StartICFiles_DIR/
else
	# replace StartICFiles with specified IC files, remove extras
	echo Using specified IC
	tar -xzvf ${ICtarfile}
	rm -rf StartICFiles_DIR/*.athdf
	mv accretion.prim.${firstfile}.athdf accretion.uov.${firstfile}.athdf StartICFiles_DIR/
	rm -rf accretion.*
fi

if ${compile}; then
	echo 'Compiling new executable...'
	python configure.py --prob ${pgen} --eos general/helmholtz_gamma_etot --coord spherical_polar --nscalars 2 -h5double -mpi -hdf5 --hdf5_path=${HDF5_HOME}
	make clean
	make
else
	echo 'Using existing executable in bin/'
fi

echo "rm -rf out_DIR/*"
rm -rf out_DIR/*
echo "rm -rf Lnu_*"
rm -rf Lnu_*
echo "rm -rf accretion.*"
rm -rf accretion.*
echo "rm -rf *.txt"
rm -rf *.txt
echo "rm -rf *.tar.gz"
rm -rf *.tar.gz
echo "mv *.out out_DIR/"
mv *.out out_DIR/

index=1
while [ $index -le ${#MPNS[@]} ]
do
	if [ $index -eq 1 ]; then 
		echo MPNS=${MPNS[index-1]}
		gifname=Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_MPNS_${MPNS[index-1]}
		DIRNAME=Lnu_${Lnu}e51_Mdot_${Mdot}_Mach_${MachNumber}_MPNS_${MPNS[index-1]}_DIR	
		if [ -d "${DIRNAME}" ]; then
    			echo "${DIRNAME} directory exists."
		else
			echo "${DIRNAME} directory does not exist. Making directory..."
			mkdir ${DIRNAME}
		fi
		MPNSdir=MPNS_${MPNS[index-1]}_DIR
		Machdir=Mach_${MachNumber}_DIR
		Mdotdir=Mdot_${Mdot}_DIR
		Lnudir=Lnu_${Lnu}_DIR
		mkdir ${ENDdatadir}/${Machdir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}/${MPNSdir}
		if ${RPNS30km}; then
			echo "Using default RPNS=30km. Creating data directory..."	
			fulldatadir=${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}/${MPNSdir}
			mkdir ${fulldatadir}
		else
			echo "Using new RPNS. Creating data directory..."
			RPNSdir=RPNS_${RPNS}_DIR
			fulldatadir=${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}/${MPNSdir}/${RPNSdir}
			mkdir ${fulldatadir}
		fi	
		# This makes the IC file that includes pressure (only want this to find initial values, not to start the code with it)
		python athdf2txt_StartIC.py ${Mdot} ${firstfile} ${Lnu} ${RPNS} ${pythondir}
		# This makes the IC for the code itself, which relies on data in a specific directory
		python athdf2txt_firststep.py ${Mdot} ${firstfile} ${Lnu} ${RPNS} ${pythondir}
		IC_trim_firstrow=$(sed '1!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${RPNS}km_StartIC.txt)
		IC_trim_lastrow=$(sed '$!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${RPNS}km_StartIC.txt)
		echo $IC_trim_firstrow > IC_trim_firstrow.txt
		echo $IC_trim_lastrow > IC_trim_lastrow.txt
		cat IC_trim_firstrow.txt
		cat IC_trim_lastrow.txt
		IC_RhoB=$(awk -F" " '{print $2}' IC_trim_firstrow.txt)
		IC_TB=$(awk -F" " '{print $4}' IC_trim_firstrow.txt)
		IC_YeB=$(awk -F" " '{print $5}' IC_trim_firstrow.txt)
		IC_vE=$(awk -F" " '{print $3}' IC_trim_lastrow.txt)
		IC_pE=$(awk -F" " '{print $6}' IC_trim_lastrow.txt)
		python Mdot_rhof_calculator_NEW.py ${Mdot} ${IC_vE} ${rMax} ${pythondir}
		# Read values from files
                IC_RhoE=$(awk -F" " '{print $1}' rho_f_${Mdot}.txt)
		# Calculating logarithmic scale for radial coordinate
		python r_logscale.py ${rMin} ${rMax} ${nR} ${pythondir}
		rScale=$(awk -F" " '{print $1}' r_scale.txt)
		echo rScale = ${rScale}
		echo rho_i = ${IC_RhoB}
		echo rho_f = ${IC_RhoE}
		echo T_i   = ${IC_TB}
		echo Ye_i  = ${IC_YeB}
		echo v_f   = ${IC_vE}
		echo p_f   = ${IC_pE}
		# Calculating GM
		python GM_calculation.py ${MPNS[index-1]} ${pythondir}
		GM=$(awk -F" " '{print $1}' GM_value.txt)
		echo GM = ${GM}
		mpiexec -n ${nCores} bin/athena -i ${athinputfile} mesh/nx1=${nR} mesh/x1min=${rMin} mesh/x1max=${rMax} mesh/x1rat=${rScale} meshblock/nx1=${nRcell} problem/rho_f=${IC_RhoE} hydro/Ye_0=${IC_YeB} problem/rho_0=${IC_RhoB} problem/T_0=${IC_TB} problem/v_f=${IC_vE} problem/p_f=${IC_pE} problem/MachNumber=${MachNumber} problem/mdot=${Mdot} output1/dt=${outputfreq} output2/dt=${outputfreq} output4/dt=${outputfreq} hydro/eos_file_name=${eosdir} time/tlim=${physicaltime} problem/L_nubar=${Lnu} problem/L_nu=${Lnu} problem/eps_nubar=${eps_nueb} problem/eps_nu=${eps_nue} problem/file=Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${RPNS}km_firststep.txt problem/MPNS=${MPNS[index-1]} problem/GM=${GM} |tee MPNS_${MPNS[index-1]}.txt
	
		# Make input file for next run	
		python athdf2txt.py ${Lnu} ${outputnumber} ${Mdot} ${RPNS} ${MPNS[index-1]} ${pythondir}
		tarfile=Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_RPNS_${RPNS}km.tar.gz
		tar -zcvf ${tarfile} accretion.*
		mv accretion.* ${DIRNAME}	
		# Make plots
		mpirun -n ${nRank} python mpipyscript_NEW.py ${DIRNAME} ${minI} ${maxI} ${nR} ${physicaltime} ${rMax} ${gifname} ${Mdot} ${pythondir} ${MachNumber} ${eps_nue} ${rMax_set} ${Lnu} ${RPNS} ${MPNS[index-1]}
		rm -rf ${DIRNAME}/accretion.*
		python gif2mp4.py ${gifname}_Multipanel
		python gif2mp4.py ${gifname}_Tadv_Theat
		python gif2mp4.py ${gifname}_Xn_Qdot
		tar -zcvf ${DIRNAME}_PLOTS.tar.gz *.png *.gif *.mp4
		mv *.png *.gif *.mp4 ${DIRNAME}
		mv ${DIRNAME}_PLOTS.tar.gz ${DIRNAME}/
		rm -rf accretion.*
		mv ${tarfile} ${DIRNAME}

		# look at vr in final zone. If Vr>0, end sript.
		FC_trim_lastrow_end=$(sed '$!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${RPNS}km_MPNS_${MPNS[index-1]}.txt)
		echo $FC_trim_lastrow_end > FC_trim_lastrow_end.txt
		cat FC_trim_lastrow_end.txt
		FC_vE=$(awk -F" " '{print $3}' FC_trim_lastrow_end.txt)
		python FC_vE_read.py ${FC_vE}
		FC_vE_FLAG=$(awk -F" " '{print $1}' FC_vE_FLAG.txt)
		echo FC_vE_FLAG = ${FC_vE_FLAG}
		mv FC_vE_FLAG.txt FC_trim_lastrow_end.txt ${DIRNAME}
		rm -rf ${fulldatadir}/*
		mv *.txt ${DIRNAME}/
		mv ${DIRNAME} ${fulldatadir}
		if [ $FC_vE_FLAG -eq 1 ]; then
			echo "Vr>0.0 detected! Ending script."	
			break
		fi
		mv ${fulldatadir}/${DIRNAME}/Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${RPNS}km_MPNS_${MPNS[index-1]}.txt .
		((index++))
	else 
		echo MPNS=${MPNS[index-1]}
		gifname=Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_MPNS_${MPNS[index-1]}
		DIRNAME=Lnu_${Lnu}e51_Mdot_${Mdot}_Mach_${MachNumber}_MPNS_${MPNS[index-1]}_DIR	
		if [ -d "${DIRNAME}" ]; then
    			echo "${DIRNAME} directory exists."
		else
			echo "${DIRNAME} directory does not exist. Making directory..."
			mkdir ${DIRNAME}
		fi	
		MPNSdir=MPNS_${MPNS[index-1]}_DIR
		Machdir=Mach_${MachNumber}_DIR
		Mdotdir=Mdot_${Mdot}_DIR
		Lnudir=Lnu_${Lnu}_DIR
		mkdir ${ENDdatadir}/${Machdir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}/${MPNSdir}
		if ${RPNS30km}; then
			echo "Using default RPNS=30km. Creating data directory..."	
			fulldatadir=${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}/${MPNSdir}
			mkdir ${fulldatadir}
		else
			echo "Using new RPNS. Creating data directory..."
			RPNSdir=RPNS_${RPNS}_DIR
			fulldatadir=${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}/${MPNSdir}/${RPNSdir}
			mkdir ${fulldatadir}
		fi

		# Calculating GM
		python GM_calculation.py ${MPNS[index-1]} ${pythondir}
		GM=$(awk -F" " '{print $1}' GM_value.txt)
		echo GM = ${GM}
		mpiexec -n ${nCores} bin/athena -i ${athinputfile} mesh/nx1=${nR} mesh/x1min=${rMin} mesh/x1max=${rMax} mesh/x1rat=${rScale} meshblock/nx1=${nRcell} problem/rho_f=${IC_RhoE} hydro/Ye_0=${IC_YeB} problem/rho_0=${IC_RhoB} problem/T_0=${IC_TB} problem/v_f=${IC_vE} problem/p_f=${IC_pE} problem/MachNumber=${MachNumber} problem/mdot=${Mdot} output1/dt=${outputfreq} output2/dt=${outputfreq} output4/dt=${outputfreq} hydro/eos_file_name=${eosdir} time/tlim=${physicaltime} problem/L_nubar=${Lnu} problem/L_nu=${Lnu} problem/eps_nubar=${eps_nueb} problem/eps_nu=${eps_nue} problem/file=Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${RPNS}km_MPNS_${MPNS[index-2]}.txt problem/MPNS=${MPNS[index-1]} problem/GM=${GM} |tee MPNS_${MPNS[index-1]}.txt	
		if [ $index -lt ${#MPNS[@]} ]; then
			python athdf2txt.py ${Lnu} ${outputnumber} ${Mdot} ${RPNS} ${MPNS[index-1]} ${pythondir}

			# look at vr in final zone. If Vr>0, end sript.
			FC_trim_lastrow_end=$(sed '$!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_MPNS_${RPNS}km.txt)
			echo $FC_trim_lastrow_end > FC_trim_lastrow_end.txt
			cat FC_trim_lastrow_end.txt
			FC_vE=$(awk -F" " '{print $3}' FC_trim_lastrow_end.txt)
			python FC_vE_read.py ${FC_vE}
			FC_vE_FLAG=$(awk -F" " '{print $1}' FC_vE_FLAG.txt)
			echo FC_vE_FLAG = ${FC_vE_FLAG}
			mv FC_vE_FLAG.txt FC_trim_lastrow_end.txt ${DIRNAME}
		else
			echo "Last step: No athdf2txt file required."
		fi
		tarfile=Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_RPNS_${RPNS}km_MPNS_${MPNS[index-1]}.tar.gz
		tar -zcvf ${tarfile} accretion.*
		mv accretion.* ${DIRNAME}
		mpirun -n ${nRank} python mpipyscript_NEW.py ${DIRNAME} ${minI} ${maxI} ${nR} ${physicaltime} ${rMax} ${gifname} ${Mdot} ${pythondir} ${MachNumber} ${eps_nue} ${rMax_set} ${Lnu} ${RPNS} ${MPNS[index-1]}
		python gif2mp4.py ${gifname}_Multipanel
		python gif2mp4.py ${gifname}_Tadv_Theat
		python gif2mp4.py ${gifname}_Xn_Qdot
		tar -zcvf ${DIRNAME}_PLOTS.tar.gz *.png *.gif *.mp4
		mv *.png *.gif *.mp4 ${DIRNAME}
		rm -rf ${DIRNAME}/accretion.*
		mv ${tarfile} ${DIRNAME}/
		mv ${DIRNAME}_PLOTS.tar.gz ${DIRNAME}/
		rm -rf ${fulldatadir}/*
		mv *.txt ${DIRNAME}	
		mv ${DIRNAME} ${fulldatadir}
		if [ $index -lt ${#MPNS[@]} ]; then
			if [ $FC_vE_FLAG -eq 1 ]; then
				echo "Vr>0.0 detected! Ending script."
				echo Mdot = ${Mdot} Msun/s
				echo Lnu  = ${Lnu}e51 erg/s
				echo Mach = ${MachNumber}
				echo RPNS = ${RPNS} km
				echo MPNS = ${MPNS[index-1]} Msun/s	
				break
			fi
			mv ${fulldatadir}/${DIRNAME}/Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${RPNS}km_MPNS_${MPNS[index-1]}.txt .
		fi
		((index++))
	fi
done
make clean
echo "1D JOBSCRIPT COMPLETE"


