#!/bin/bash
#SBATCH --account=PAS2229
#SBATCH --time=3:00:00
#SBATCH --job-name=athena
#SBATCH --nodes=7
#SBATCH --ntasks=256
#SBATCH --mail-type=ALL
#SBATCH --export=ALL
#SBATCH --open-mode=append

module load intel/18.0.3
module load intelmpi/2019.7
module load hdf5
module load miniconda3
unset I_MPI_PMI_LIBRARY
set -x
cd $SLURM_SUBMIT_DIR

conda create -n hdf5 python=3.9.7 hdf5=1.10.6 h5py=3.6.0
conda create -n conda_env
source activate conda_env
conda activate hdf5
conda install mpi4py
conda install numpy
conda install hdf5
conda install matplotlib
conda install scipy
conda install -c conda-forge moviepy

###### MAIN OPTIONS ###
Lnu=10
Mdot=0.7
MachNumber=2.0
R_PNS=(30 31)
physicaltime=3.0e0
outputfreq=3.0e-2
minI=0
maxI=99
nRank=100
eps_nue=12.6156
eps_nueb=18.9234
compile=true
use30kmIC=true
useDefaultIC=true
#### CODE PARAMETERS ####
firstfile=00100
outputnumber=00100
athinputfile=athinput.accretion_MACH_9_25_2023
rMax=1.0e8
rMax_set=220.0 #maximum Radius for some radial plots, in km
nR=256
nRcell=2
nCores=128
pgen=accretion_SingleNR_FixedKappa #accretion_Mach_FullDefinition_Tfloat
pythondir=vis/python
eosdir=../eos_DIR/helm_table.dat
ENDdatadir=../1D_OUTPUT_RPNS_DIR
ENDdatadir_IC=../1D_OUTPUT_DIR

# Get IC files and stash them in StartIC_DIR
if ${use30kmIC}; then
	echo Using IC from 1D_OUTPUT_DIR...
	ICdir=${ENDdatadir_IC}/Mach_${MachNumber}_DIR/Mdot_${Mdot}_DIR/Lnu_${Lnu}_DIR/Lnu_${Lnu}e51_Mdot_${Mdot}_Mach_${MachNumber}_DIR
	ICtarfile=${ICdir}/Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_RPNS_${R_PNS[0]}km.tar.gz
else
	echo Using IC from 1D_OUTPUT_RPNS_DIR...
	ICdir=${ENDdatadir}/Mach_${MachNumber}_DIR/Mdot_${Mdot}_DIR/Lnu_${Lnu}_DIR/RPNS_${R_PNS[0]}_DIR/Lnu_${Lnu}e51_Mdot_${Mdot}_Mach_${MachNumber}_DIR	
	ICtarfile=${ICdir}/Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_RPNS_${R_PNS[0]}km.tar.gz
fi
if ${useDefaultIC}; then
	# replace StartICFiles with default IC files
	echo Using default IC
	cp ../default_IC_DIR/*.athdf .	
	rm -rf StartICFiles_DIR/*.athdf
	mv accretion.prim.${firstfile}.athdf accretion.uov.${firstfile}.athdf StartICFiles_DIR/
else
	# replace StartICFiles with specified IC files, remove extras
	echo Using specified IC
	tar -xzvf ${ICtarfile}
	rm -rf StartICFiles_DIR/*.athdf
	mv accretion.prim.${firstfile}.athdf accretion.uov.${firstfile}.athdf StartICFiles_DIR/
	rm -rf accretion.*
fi

if ${compile}; then
	echo 'Compiling new executable...'
	python configure.py --prob ${pgen} --eos general/helmholtz_gamma_etot --coord spherical_polar --nscalars 2 -h5double -mpi -hdf5 --hdf5_path=${HDF5_HOME}
	make clean
	make
else
	echo 'Using existing executable in bin/'
fi

echo "rm -rf out_DIR/*.out"
rm -rf out_DIR/*.out
echo "rm -rf Lnu_*"
rm -rf Lnu_*
echo "rm -rf accretion.*"
rm -rf accretion.*
echo "rm -rf *.txt"
rm -rf *.txt
echo "rm -rf *.tar.gz"
rm -rf *.tar.gz
echo "mv *.out out_DIR/"
mv *.out out_DIR/

index=1
while [ $index -le ${#R_PNS[@]} ]
do
	if [ $index -eq 1 ]; then
	        echo R_PNS=${R_PNS[index-1]}
		gifname=Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}
		DIRNAME=Lnu_${Lnu}e51_Mdot_${Mdot}_Mach_${MachNumber}_DIR		
		if [ -d "${DIRNAME}" ]; then
    			echo "${DIRNAME} directory exists."
		else
			echo "${DIRNAME} directory does not exist. Making directory..."
			mkdir ${DIRNAME}
		fi
		Machdir=Mach_${MachNumber}_DIR
		Mdotdir=Mdot_${Mdot}_DIR
		Lnudir=Lnu_${Lnu}_DIR
		Rpnsdir=RPNS_${R_PNS[index-1]}_DIR
		mkdir ${ENDdatadir}/${Machdir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}
		fulldatadir=${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}/${Rpnsdir}
		mkdir ${fulldatadir}
		# This makes the IC file that includes pressure (only want this to find initial values, not to start the code with it)
		python athdf2txt_StartIC.py ${Mdot} ${firstfile} ${Lnu} ${R_PNS[0]} ${pythondir}
		# This makes the IC for the code itself, which relies on data in a specific directory
		python athdf2txt_firststep.py ${Mdot} ${firstfile} ${Lnu} ${R_PNS[0]} ${pythondir}
		IC_trim_firstrow=$(sed '1!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km_StartIC.txt)
		IC_trim_lastrow=$(sed '$!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km_StartIC.txt)
		echo $IC_trim_firstrow > IC_trim_firstrow.txt
		echo $IC_trim_lastrow > IC_trim_lastrow.txt
		cat IC_trim_firstrow.txt
		cat IC_trim_lastrow.txt
		IC_RhoB=$(awk -F" " '{print $2}' IC_trim_firstrow.txt)
		IC_TB=$(awk -F" " '{print $4}' IC_trim_firstrow.txt)
		IC_YeB=$(awk -F" " '{print $5}' IC_trim_firstrow.txt)
		IC_vE=$(awk -F" " '{print $3}' IC_trim_lastrow.txt)
		IC_pE=$(awk -F" " '{print $6}' IC_trim_lastrow.txt)
		python Mdot_rhof_calculator_NEW.py ${Mdot} ${IC_vE} ${rMax} ${pythondir}
		# Read values from files
                IC_RhoE=$(awk -F" " '{print $1}' rho_f_${Mdot}.txt)
		# Calculating logarithmic scale for radial coordinate
		python r_logscale.py ${R_PNS[index-1]} ${rMax} ${nR} ${pythondir}
		rScale=$(awk -F" " '{print $1}' r_scale.txt)
		echo rScale = ${rScale}
		echo rho_i = ${IC_RhoB}
		echo rho_f = ${IC_RhoE}
		echo T_i   = ${IC_TB}
		echo Ye_i  = ${IC_YeB}
		echo v_f   = ${IC_vE}
		echo p_f   = ${IC_pE}

		mpiexec -n ${nCores} bin/athena -i ${athinputfile} mesh/nx1=${nR} mesh/x1min=${R_PNS[index-1]}.0e5 mesh/x1max=${rMax} mesh/x1rat=${rScale} meshblock/nx1=${nRcell} problem/rho_f=${IC_RhoE} hydro/Ye_0=${IC_YeB} problem/rho_0=${IC_RhoB} problem/T_0=${IC_TB} problem/v_f=${IC_vE} problem/p_f=${IC_pE} problem/MachNumber=${MachNumber} problem/mdot=${Mdot} output1/dt=${outputfreq} output2/dt=${outputfreq} output4/dt=${outputfreq} hydro/eos_file_name=${eosdir} time/tlim=${physicaltime} problem/L_nubar=${Lnu} problem/L_nu=${Lnu} problem/eps_nubar=${eps_nueb} problem/eps_nu=${eps_nue} problem/file=Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km_firststep.txt |tee R_PNS_${R_PNS[index-1]}_OUTPUT.txt

		python athdf2txt.py ${Lnu} ${outputnumber} ${Mdot} ${R_PNS[index-1]} ${pythondir}	
		tarfile=Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_RPNS_${R_PNS[index-1]}km.tar.gz
		tar -zcvf ${tarfile} accretion.*
		cp accretion.* ${DIRNAME}
		# Make plots
		mpirun -n ${nRank} python mpipyscript_NEW.py ${DIRNAME} ${minI} ${maxI} ${nR} ${physicaltime} ${rMax} ${gifname} ${Mdot} ${pythondir} ${MachNumber} ${eps_nue} ${rMax_set} ${Lnu} ${R_PNS[index-1]}
		python gif2mp4.py ${gifname}_Multipanel
		python gif2mp4.py ${gifname}_Tadv_Theat
		python gif2mp4.py ${gifname}_Xn_Qdot
		rm -rf ${DIRNAME}/accretion.*
		tar -zcvf ${DIRNAME}_PLOTS.tar.gz *.png *.gif *.mp4
		mv *.png *.gif *.mp4 ${DIRNAME}
		mv ${DIRNAME}_PLOTS.tar.gz ${DIRNAME}/
		mv ${tarfile} ${DIRNAME}	

		# look at vr in final zone. If Vr>0, end sript.
		FC_trim_lastrow_end=$(sed '$!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km.txt)
		echo $FC_trim_lastrow_end > FC_trim_lastrow_end.txt
		cat FC_trim_lastrow_end.txt
		FC_vE=$(awk -F" " '{print $3}' FC_trim_lastrow_end.txt)
		python FC_vE_read.py ${FC_vE}
		FC_vE_FLAG=$(awk -F" " '{print $1}' FC_vE_FLAG.txt)
		echo FC_vE_FLAG = ${FC_vE_FLAG}
		mv FC_vE_FLAG.txt FC_trim_lastrow_end.txt ${DIRNAME}
		rm -rf ${fulldatadir}/*
		mv *.txt ${DIRNAME}/
		mv ${DIRNAME} ${fulldatadir}
		if [ $FC_vE_FLAG -eq 1 ]; then
			echo "Vr>0.0 detected! Ending script."	
			break
		fi	
		# Move the input file back to the working directory for the next step if the script is still running
		mv ${fulldatadir}/${DIRNAME}/Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km.txt .
		((index++))
	else
	        echo R_PNS=${R_PNS[index-1]}	
		DIRNAME=Lnu_${Lnu}e51_Mdot_${Mdot}_Mach_${MachNumber}_DIR
		
		if [ -d "${DIRNAME}" ]; then
    			echo "${DIRNAME} directory exists."
		else
			echo "${DIRNAME} directory does not exist. Making directory..."
			mkdir ${DIRNAME}
		fi
		gifname=Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}
		Machdir=Mach_${MachNumber}_DIR
		Mdotdir=Mdot_${Mdot}_DIR
		Lnudir=Lnu_${Lnu}_DIR
		Rpnsdir=RPNS_${R_PNS[index-1]}_DIR
		mkdir ${ENDdatadir}/${Machdir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}
		mkdir ${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}
		fulldatadir=${ENDdatadir}/${Machdir}/${Mdotdir}/${Lnudir}/${Rpnsdir}
		mkdir ${fulldatadir}
		python increaseRPNS_interp.py ${R_PNS[index-1]} ${outputnumber} ${Lnu} ${Mdot} ${pythondir}
		python r_logscale.py ${R_PNS[index-1]} ${rMax} ${nR} ${pythondir}
		rScale=$(awk -F" " '{print $1}' r_scale.txt)
		python Mdot_rhof_calculator_NEW.py ${Mdot} ${IC_vE} ${rMax} ${pythondir}	
                IC_RhoE=$(awk -F" " '{print $1}' rho_f_${Mdot}.txt)
		IC_trim=$(sed '1!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km_extrapolate.txt)
		echo $IC_trim > IC_trim.txt
 		cat IC_trim.txt
		IC_RhoB=$(awk -F" " '{print $2}' IC_trim.txt)
		IC_TB=$(awk -F" " '{print $4}' IC_trim.txt)
		IC_YeB=$(awk -F" " '{print $5}' IC_trim.txt)	
		rm -rf accretion.*
		
		mpiexec -n ${nCores} bin/athena -i ${athinputfile} mesh/nx1=${nR} mesh/x1min=${R_PNS[index-1]}.0e5 mesh/x1max=${rMax} mesh/x1rat=${rScale} meshblock/nx1=${nRcell} problem/rho_f=${IC_RhoE} hydro/Ye_0=${IC_YeB} problem/rho_0=${IC_RhoB} problem/T_0=${IC_TB} problem/v_f=${IC_vE} problem/p_f=${IC_pE} problem/MachNumber=${MachNumber} problem/mdot=${Mdot} output1/dt=${outputfreq} output2/dt=${outputfreq} output4/dt=${outputfreq} hydro/eos_file_name=${eosdir} time/tlim=${physicaltime} problem/L_nubar=${Lnu} problem/L_nu=${Lnu} problem/eps_nubar=${eps_nueb} problem/eps_nu=${eps_nue} problem/file=Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km_extrapolate.txt |tee R_PNS_${R_PNS[index-1]}_OUTPUT.txt
		
		if [ $index -lt ${#R_PNS[@]} ]; then
			python athdf2txt.py ${Lnu} ${outputnumber} ${Mdot} ${R_PNS[index-1]} ${pythondir}

			# look at vr in final zone. If Vr>0, end sript.
			FC_trim_lastrow_end=$(sed '$!d' Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km.txt)
			echo $FC_trim_lastrow_end > FC_trim_lastrow_end.txt
			cat FC_trim_lastrow_end.txt
			FC_vE=$(awk -F" " '{print $3}' FC_trim_lastrow_end.txt)
			python FC_vE_read.py ${FC_vE}
			FC_vE_FLAG=$(awk -F" " '{print $1}' FC_vE_FLAG.txt)
			echo FC_vE_FLAG = ${FC_vE_FLAG}
			mv FC_vE_FLAG.txt FC_trim_lastrow_end.txt ${DIRNAME}
		else
			echo "Last step: No athdf2txt file required."
		fi
		tarfile=Lnu_${Lnu}_Mdot_${Mdot}_Mach_${MachNumber}_RPNS_${R_PNS[index-1]}km.tar.gz
		tar -zcvf ${tarfile} accretion.*
		cp accretion.* ${DIRNAME}
		mpirun -n ${nRank} python mpipyscript_NEW.py ${DIRNAME} ${minI} ${maxI} ${nR} ${physicaltime} ${rMax} ${gifname} ${Mdot} ${pythondir} ${MachNumber} ${eps_nue} ${rMax_set} ${Lnu} ${R_PNS[index-1]}
		python gif2mp4.py ${gifname}_Multipanel
		python gif2mp4.py ${gifname}_Tadv_Theat
		python gif2mp4.py ${gifname}_Xn_Qdot
		tar -zcvf ${DIRNAME}_PLOTS.tar.gz *.png *.gif *.mp4
		mv *.png *.gif *.mp4 ${DIRNAME}
		rm -rf ${DIRNAME}/accretion.*	
		mv ${tarfile} ${DIRNAME}/
		mv ${DIRNAME}_PLOTS.tar.gz ${DIRNAME}/
		rm -rf ${fulldatadir}/*
		mv *.txt ${DIRNAME}
		mv ${DIRNAME} ${fulldatadir}
		if [ $index -lt ${#R_PNS[@]} ]; then
			if [ $FC_vE_FLAG -eq 1 ]; then	
				echo "Vr>0.0 detected! Ending script."
				echo Mdot = ${Mdot} Msun/s
				echo Lnu  = ${Lnu[index-1]}e51 erg/s
				echo Mach = ${MachNumber}
				echo RPNS = ${R_PNS} km	
				break
			fi
			mv ${fulldatadir}/${DIRNAME}/Lnu_${Lnu}e51_Mdot_${Mdot}_RPNS_${R_PNS[index-1]}km.txt .
		fi
		((index++))
	fi
done
make clean
rm -rf accretion.*
echo "1D JOBSCRIPT COMPLETE"
